# Generated by Django 2.1.4 on 2018-12-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(verbose_name='錯誤訊息')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='錯誤時間')),
                ('checked', models.BooleanField(default=False, verbose_name='已檢查')),
            ],
        ),
    ]
